<?php
function ngo_relation_menu() {
  $items = array();
  $items['admin/ngo_cause_relation'] = array( //this creates a URL that will call this form at "examples/form-example"
    'title' => 'NGO and cause relation', //page title
    'description' => 'Relation between NGO and cause',
    'page callback' => 'drupal_get_form', //this is the function that will be called when the page is accessed.  for a form, use drupal_get_form
    'page arguments' => array('ngo_relation_form'), //put the name of the form here
    'access callback' => TRUE
  );
  return $items;
}
function ngo_relation_form($form, &$form_state) {
  // Return all nids of nodes of type "page".
$ngo_nids = db_select('node', 'n')
    ->fields('n', array('nid'))
    ->fields('n', array('type'))
    ->fields('n', array('title'))    
    ->condition('n.type', 'ngo')
    ->execute()
    ->fetchCol(); // returns an indexed array
// Now return the node objects.
$ngo_nodes = node_load_multiple($ngo_nids);
$ngo_list = array();
$cause_list = array();
$cause_nids = db_select('node', 'n')
    ->fields('n', array('nid'))
    ->fields('n', array('type'))
    ->fields('n', array('title'))    
    ->condition('n.type', 'cause')
    ->execute()
    ->fetchCol(); // returns an indexed array
// Now return the node objects.
$cause_nodes = node_load_multiple($cause_nids);

$ngo_list[] = 'Please Select';
if(sizeof($ngo_nodes) > 0) {
    foreach($ngo_nodes as $key => $ngo_array) {
        $ngo_list[$key] = $ngo_array->title;
    }
}

if(sizeof($cause_nodes) > 0) {
    foreach($cause_nodes as $key => $cause_array) {
        $cause_list[$key] = $cause_array->title;
    }
}
  $form['ngo_id'] = array(
    '#type' => 'select',
    '#title' => t('NGO'),
    '#default_value' => '',
    '#options' => $ngo_list,
    '#required' => TRUE  
  );
  $form['cause_id'] = array(
    '#type' => 'select',
    '#title' => t('Cause'),
    '#default_value' => '',
    '#options' => $cause_list,
    '#multiple' => TRUE,  
    '#required' => TRUE  
  );
  $form['submit_button'] = array(
    '#type' => 'submit',
    '#value' => t('Save relationship'),
    );
  return $form;
}
function ngo_relation_form_validate($form, &$form_state) {
}
function ngo_relation_form_submit($form, &$form_state) {
}

 // during hook_form_alter, make sure $form & $form_state arguments are passed by reference
function ngo_relation_form_alter(&$form, &$form_state, $form_id) {
 //echo $form_id; print_r($form_state);
  // print form_id
  // drupal_set_message('<pre>' . print_r($form_id,true) . '</pre>');
  // drupal_set_message('<pre>' . print_r($form,true) . '</pre>');
 
  if ($form_id == 'campaign_node_form') {
    $form['actions']['submit']['#submit'][] = '_campaign_extra_submit_handler';     
  }
  if ($form_id == 'ngo_image_gallery_node_form') {
    $form['actions']['submit']['#submit'][] = '_ngo_image_extra_submit_handler';     
  }
  if ($form_id == 'forum_node_form') {
    $form['actions']['submit']['#submit'][] = '_forum_extra_submit_handler';     
  }
  if ($form_id == 'ngo_financial_data_node_form') {
    $form['actions']['submit']['#submit'][] = '_forum_extra_submit_handler';     
  }
  
}
 
// extra submit handler callback function
function _campaign_extra_submit_handler(&$form, &$form_state) {
    $lang = $form['field_ngo']['#language'];
    $ngo_id = $form_state['values']['field_ngo'][$lang][0]['nid'];
    if($ngo_id != '' && $ngo_id != 0) {
        unset($_GET['destination']);
	$form_state['redirect'] = Array('admin/admin-campaign', array('query' => array('field_ngo_nid' => $ngo_id)));
    }	
}
// extra submit handler callback function
function _ngo_image_extra_submit_handler(&$form, &$form_state) {
    $lang = $form['field_ngo']['#language'];
    $ngo_id = $form_state['values']['field_ngo'][$lang][0]['nid'];
    if($ngo_id != '' && $ngo_id != 0) {
        unset($_GET['destination']);
	$form_state['redirect'] = Array('admin/admin-ngo-image-gallery', array('query' => array('field_ngo_nid' => $ngo_id)));
    }	
}
// extra submit handler callback function
function _forum_extra_submit_handler(&$form, &$form_state) {
    $lang = $form['field_ngo']['#language'];
    $ngo_id = $form_state['values']['field_ngo'][$lang][0]['nid'];
    if($ngo_id != '' && $ngo_id != 0) {
        unset($_GET['destination']);
	$form_state['redirect'] = Array('admin/manage_forum', array('query' => array('field_ngo_nid' => $ngo_id)));
    }	
}
// extra submit handler callback function
function _ngo_financial_extra_submit_handler(&$form, &$form_state) {
    $lang = $form['field_ngo']['#language'];
    $ngo_id = $form_state['values']['field_ngo'][$lang][0]['nid'];
    if($ngo_id != '' && $ngo_id != 0) {
        unset($_GET['destination']);
	$form_state['redirect'] = Array('admin/ngo-financial-data', array('query' => array('field_ngo_nid' => $ngo_id)));
    }	
}

function ngo_relation_list_text_allowed_values($field){
  if($field['field_name'] == 'field_year_of_establishment'){
    return array('first','second','third');
  }
}
function _ngo_relation_get_all_year() {
    $options = array();
    $range = 100;
    $current_year = date("Y");
    $start_year = ($current_year - $range);
    for($i = $start_year; $i <= $current_year; $i++) {
        $options[$i] = $i;
    }
    return $options;
}
function ngo_relation_block_info() {
  $blocks['people_cause_campaign_list'] = array(
    'info' => t('People, Cause & Campaign list'),
    'cache' => DRUPAL_NO_CACHE, //see link below for what this does.
    //many other properties can be added here in this way.
    //for all options, http://api.drupal.org/api/drupal/modules--block--block.api.php/function/hook_block_info/7
  );  
  return $blocks;
}
function ngo_relation_block_view($delta) {
  $block = array();
  //delta is your block name. then just set it equal to your return functions.
  switch ($delta) {
    case 'people_cause_campaign_list':
      //use helper functions to set the blocks. Cleaner.
      $block = _ngo_people_cause_campaign_list();
      break;
  }
  return $block;
}
function _ngo_people_cause_campaign_list() {
  $content = '';  
  $content .= '';
  $content .= _ngo_block_cause_list();
  //this $block['content'] uses the old way, just a regular string.
  $block['content'] = $content;
  $block['subject'] = 'title';
  return $block;
    
}
function _ngo_block_cause_list() {
    $output = '';
 $type = 'cause';
 
 $query = new EntityFieldQuery();
$query->entityCondition('entity_type', 'node')
  ->propertyCondition('status', 1)
  ->propertyCondition('type', array($type))
  ->addTag('random')
  ->range(0, 5);
$result = $query->execute();
 
 $nodes = node_load_multiple(array_keys($result['node']));
 
  $output .= '<div class="cause_lists">';
 foreach($nodes as $key => $node_obj) {
     $title = $node_obj->title;
    $nid = $node_obj->nid;
    $icon = $node_obj->field_cause_icon[$node_obj->language][0];
    $ngo_count = 0;
    $row = (object)db_query("SELECT count({field_data_field_cause}.entity_id) as ngo_count from {field_data_field_cause} WHERE bundle = :bundle and field_cause_nid = :nid GROUP BY field_cause_nid LIMIT 1", array(":bundle" => 'ngo', ":nid" => $nid))->fetchAssoc();
    if(isset($row->ngo_count)) {
        $ngo_count = $row->ngo_count;
    }
    $output .= '<div class="cause_list">';
     $output .= '<div class="node_title">' . $title . '</div>';
     if(isset($icon['uri'])) {
      
     $output .= '<div class="node_icon"><img src="' . image_style_url('thumbnail', $icon['uri']) . ' /></div>';
     }
     $output .= '<div class="node_ngocount">NGO: ' . $ngo_count . '</div>';
     $output .= '</div>';
 }
 $output .= '</div>';
 return $output;
}
function _ngo_block_campaign_list() {
 $type = 'campaign';   
 $nodes = node_load_multiple(array(), array('type' => $type));
 print_r($nodes);
}